// <auto-generated />
using System;
using GriffGym.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GriffGym.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GriffGymDbContext))]
    partial class GriffGymDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("griffgym_sync_version");

            modelBuilder.Entity("GriffGym.Infrastructure.Persistence.Entities.ExerciseLogRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExerciseCategory")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("exercise_category");

                    b.Property<Guid?>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("exercise_name");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<Guid>("WorkoutSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_session_id");

                    b.HasKey("Id")
                        .HasName("pk_exercise_log");

                    b.HasIndex("ExerciseId")
                        .HasDatabaseName("ix_exercise_log_exercise_id");

                    b.HasIndex("WorkoutSessionId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ix_exercise_log_workout_session_id_position");

                    b.ToTable("exercise_log", (string)null);
                });

            modelBuilder.Entity("GriffGym.Infrastructure.Persistence.Entities.ExerciseRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<long>("SyncVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("sync_version");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_exercise");

                    b.HasIndex("SyncVersion")
                        .HasDatabaseName("ix_exercise_sync_version");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_exercise_user_id_name");

                    b.ToTable("exercise", (string)null);
                });

            modelBuilder.Entity("GriffGym.Infrastructure.Persistence.Entities.ExerciseTemplateRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExerciseCategory")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("exercise_category");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("exercise_name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<Guid>("WorkoutTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_template_id");

                    b.HasKey("Id")
                        .HasName("pk_exercise_template");

                    b.HasIndex("ExerciseId")
                        .HasDatabaseName("ix_exercise_template_exercise_id");

                    b.HasIndex("WorkoutTemplateId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ix_exercise_template_workout_template_id_position");

                    b.ToTable("exercise_template", (string)null);
                });

            modelBuilder.Entity("GriffGym.Infrastructure.Persistence.Entities.PlannedSetRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ExerciseTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_template_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<int?>("Reps")
                        .HasColumnType("integer")
                        .HasColumnName("reps");

                    b.Property<decimal?>("RpeMax")
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("rpe_max");

                    b.Property<decimal?>("RpeMin")
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("rpe_min");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id")
                        .HasName("pk_planned_set");

                    b.HasIndex("ExerciseTemplateId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ix_planned_set_exercise_template_id_position");

                    b.ToTable("planned_set", (string)null);
                });

            modelBuilder.Entity("GriffGym.Infrastructure.Persistence.Entities.ReferenceMaxRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Lift")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("lift");

                    b.Property<long>("SyncVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("sync_version");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<decimal>("ValueKg")
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("value_kg");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_reference_max");

                    b.HasIndex("SyncVersion")
                        .HasDatabaseName("ix_reference_max_sync_version");

                    b.HasIndex("UserId", "Lift")
                        .IsUnique()
                        .HasDatabaseName("ix_reference_max_user_id_lift");

                    b.ToTable("reference_max", (string)null);
                });

            modelBuilder.Entity("GriffGym.Infrastructure.Persistence.Entities.RefreshTokenRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<string>("RevocationReason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_token");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_token_token_hash");

                    b.HasIndex("UserId", "ExpiresAtUtc")
                        .HasDatabaseName("ix_refresh_token_user_id_expires_at_utc");

                    b.ToTable("refresh_token", (string)null);
                });

            modelBuilder.Entity("GriffGym.Infrastructure.Persistence.Entities.SetLogRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ActualReps")
                        .HasColumnType("integer")
                        .HasColumnName("actual_reps");

                    b.Property<decimal?>("ActualRpe")
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("actual_rpe");

                    b.Property<decimal?>("ActualWeightKg")
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("actual_weight_kg");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean")
                        .HasColumnName("completed");

                    b.Property<Guid>("ExerciseLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_log_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<int?>("PlannedReps")
                        .HasColumnType("integer")
                        .HasColumnName("planned_reps");

                    b.Property<decimal?>("PlannedRpeMax")
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("planned_rpe_max");

                    b.Property<decimal?>("PlannedRpeMin")
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("planned_rpe_min");

                    b.Property<decimal?>("PlannedWeightKg")
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("planned_weight_kg");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("Id")
                        .HasName("pk_set_log");

                    b.HasIndex("ExerciseLogId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ix_set_log_exercise_log_id_position");

                    b.ToTable("set_log", (string)null);
                });

            modelBuilder.Entity("GriffGym.Infrastructure.Persistence.Entities.TrainingCycleRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BenchPressReferenceMaxKg")
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("bench_press_reference_max_kg");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("CycleNumber")
                        .HasColumnType("integer")
                        .HasColumnName("cycle_number");

                    b.Property<decimal>("DeadliftReferenceMaxKg")
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("deadlift_reference_max_kg");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<decimal>("SquatReferenceMaxKg")
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("squat_reference_max_kg");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<long>("SyncVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("sync_version");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_training_cycle");

                    b.HasIndex("SyncVersion")
                        .HasDatabaseName("ix_training_cycle_sync_version");

                    b.HasIndex("UserId", "CycleNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_training_cycle_user_id_cycle_number");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_training_cycle_user_id_status");

                    b.ToTable("training_cycle", (string)null);
                });

            modelBuilder.Entity("GriffGym.Infrastructure.Persistence.Entities.TrainingProgramRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CurrentWorkoutTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_workout_template_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TrainingCycleId")
                        .HasColumnType("uuid")
                        .HasColumnName("training_cycle_id");

                    b.HasKey("Id")
                        .HasName("pk_training_program");

                    b.HasIndex("TrainingCycleId")
                        .IsUnique()
                        .HasDatabaseName("ix_training_program_training_cycle_id");

                    b.ToTable("training_program", (string)null);
                });

            modelBuilder.Entity("GriffGym.Infrastructure.Persistence.Entities.TrainingWeekRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("label");

                    b.Property<Guid>("TrainingProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("training_program_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer")
                        .HasColumnName("week_number");

                    b.HasKey("Id")
                        .HasName("pk_training_week");

                    b.HasIndex("TrainingProgramId", "WeekNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_training_week_training_program_id_week_number");

                    b.ToTable("training_week", (string)null);
                });

            modelBuilder.Entity("GriffGym.Infrastructure.Persistence.Entities.UserRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("security_stamp");

                    b.Property<long>("SyncVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("sync_version");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_user_normalized_email");

                    b.HasIndex("SyncVersion")
                        .HasDatabaseName("ix_user_sync_version");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("GriffGym.Infrastructure.Persistence.Entities.WorkoutSessionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer")
                        .HasColumnName("day_number");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at_utc");

                    b.Property<bool>("IsDeload")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deload");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("PerformedOn")
                        .HasColumnType("date")
                        .HasColumnName("performed_on");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<long>("SyncVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("sync_version");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<decimal?>("TotalVolumeKg")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_volume_kg");

                    b.Property<Guid?>("TrainingCycleId")
                        .HasColumnType("uuid")
                        .HasColumnName("training_cycle_id");

                    b.Property<Guid?>("TrainingWeekId")
                        .HasColumnType("uuid")
                        .HasColumnName("training_week_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer")
                        .HasColumnName("week_number");

                    b.Property<Guid?>("WorkoutTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_template_id");

                    b.HasKey("Id")
                        .HasName("pk_workout_session");

                    b.HasIndex("SyncVersion")
                        .HasDatabaseName("ix_workout_session_sync_version");

                    b.HasIndex("TrainingCycleId")
                        .HasDatabaseName("ix_workout_session_training_cycle_id");

                    b.HasIndex("TrainingWeekId")
                        .HasDatabaseName("ix_workout_session_training_week_id");

                    b.HasIndex("WorkoutTemplateId")
                        .HasDatabaseName("ix_workout_session_workout_template_id");

                    b.HasIndex("UserId", "PerformedOn")
                        .HasDatabaseName("ix_workout_session_user_id_performed_on");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_workout_session_user_id_status");

                    b.HasIndex("UserId", "TrainingCycleId", "WeekNumber")
                        .HasDatabaseName("ix_workout_session_user_id_training_cycle_id_week_number");

                    b.ToTable("workout_session", (string)null);
                });

            modelBuilder.Entity("GriffGym.Infrastructure.Persistence.Entities.WorkoutTemplateRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer")
                        .HasColumnName("day_number");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid>("TrainingWeekId")
                        .HasColumnType("uuid")
                        .HasColumnName("training_week_id");

                    b.HasKey("Id")
                        .HasName("pk_workout_template");

                    b.HasIndex("TrainingWeekId", "DayNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_workout_template_training_week_id_day_number");

                    b.ToTable("workout_template", (string)null);
                });

            modelBuilder.Entity("GriffGym.Infrastructure.Persistence.Entities.ExerciseLogRecord", b =>
                {
                    b.HasOne("GriffGym.Infrastructure.Persistence.Entities.ExerciseRecord", null)
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_exercise_log_exercise_exercise_id");

                    b.HasOne("GriffGym.Infrastructure.Persistence.Entities.WorkoutSessionRecord", "Session")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exercise_log_workout_session_workout_session_id");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("GriffGym.Infrastructure.Persistence.Entities.ExerciseRecord", b =>
                {
                    b.HasOne("GriffGym.Infrastructure.Persistence.Entities.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exercise_user_user_id");
                });

            modelBuilder.Entity("GriffGym.Infrastructure.Persistence.Entities.ExerciseTemplateRecord", b =>
                {
                    b.HasOne("GriffGym.Infrastructure.Persistence.Entities.ExerciseRecord", null)
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exercise_template_exercise_exercise_id");

                    b.HasOne("GriffGym.Infrastructure.Persistence.Entities.WorkoutTemplateRecord", "Workout")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exercise_template_workout_template_workout_template_id");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("GriffGym.Infrastructure.Persistence.Entities.PlannedSetRecord", b =>
                {
                    b.HasOne("GriffGym.Infrastructure.Persistence.Entities.ExerciseTemplateRecord", "ExerciseTemplate")
                        .WithMany("PlannedSets")
                        .HasForeignKey("ExerciseTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_planned_set_exercise_template_exercise_template_id");

                    b.Navigation("ExerciseTemplate");
                });

            modelBuilder.Entity("GriffGym.Infrastructure.Persistence.Entities.ReferenceMaxRecord", b =>
                {
                    b.HasOne("GriffGym.Infrastructure.Persistence.Entities.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reference_max_user_user_id");
                });

            modelBuilder.Entity("GriffGym.Infrastructure.Persistence.Entities.RefreshTokenRecord", b =>
                {
                    b.HasOne("GriffGym.Infrastructure.Persistence.Entities.UserRecord", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_token_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GriffGym.Infrastructure.Persistence.Entities.SetLogRecord", b =>
                {
                    b.HasOne("GriffGym.Infrastructure.Persistence.Entities.ExerciseLogRecord", "ExerciseLog")
                        .WithMany("Sets")
                        .HasForeignKey("ExerciseLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_set_log_exercise_log_exercise_log_id");

                    b.Navigation("ExerciseLog");
                });

            modelBuilder.Entity("GriffGym.Infrastructure.Persistence.Entities.TrainingCycleRecord", b =>
                {
                    b.HasOne("GriffGym.Infrastructure.Persistence.Entities.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_training_cycle_user_user_id");
                });

            modelBuilder.Entity("GriffGym.Infrastructure.Persistence.Entities.TrainingProgramRecord", b =>
                {
                    b.HasOne("GriffGym.Infrastructure.Persistence.Entities.TrainingCycleRecord", "Cycle")
                        .WithOne("Program")
                        .HasForeignKey("GriffGym.Infrastructure.Persistence.Entities.TrainingProgramRecord", "TrainingCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_training_program_training_cycle_training_cycle_id");

                    b.Navigation("Cycle");
                });

            modelBuilder.Entity("GriffGym.Infrastructure.Persistence.Entities.TrainingWeekRecord", b =>
                {
                    b.HasOne("GriffGym.Infrastructure.Persistence.Entities.TrainingProgramRecord", "Program")
                        .WithMany("Weeks")
                        .HasForeignKey("TrainingProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_training_week_training_program_training_program_id");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("GriffGym.Infrastructure.Persistence.Entities.WorkoutSessionRecord", b =>
                {
                    b.HasOne("GriffGym.Infrastructure.Persistence.Entities.TrainingCycleRecord", null)
                        .WithMany()
                        .HasForeignKey("TrainingCycleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_workout_session_training_cycle_training_cycle_id");

                    b.HasOne("GriffGym.Infrastructure.Persistence.Entities.TrainingWeekRecord", null)
                        .WithMany()
                        .HasForeignKey("TrainingWeekId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_workout_session_training_week_training_week_id");

                    b.HasOne("GriffGym.Infrastructure.Persistence.Entities.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workout_session_user_user_id");

                    b.HasOne("GriffGym.Infrastructure.Persistence.Entities.WorkoutTemplateRecord", null)
                        .WithMany()
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_workout_session_workout_template_workout_template_id");
                });

            modelBuilder.Entity("GriffGym.Infrastructure.Persistence.Entities.WorkoutTemplateRecord", b =>
                {
                    b.HasOne("GriffGym.Infrastructure.Persistence.Entities.TrainingWeekRecord", "Week")
                        .WithMany("Workouts")
                        .HasForeignKey("TrainingWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workout_template_training_week_training_week_id");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("GriffGym.Infrastructure.Persistence.Entities.ExerciseLogRecord", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("GriffGym.Infrastructure.Persistence.Entities.ExerciseTemplateRecord", b =>
                {
                    b.Navigation("PlannedSets");
                });

            modelBuilder.Entity("GriffGym.Infrastructure.Persistence.Entities.TrainingCycleRecord", b =>
                {
                    b.Navigation("Program");
                });

            modelBuilder.Entity("GriffGym.Infrastructure.Persistence.Entities.TrainingProgramRecord", b =>
                {
                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("GriffGym.Infrastructure.Persistence.Entities.TrainingWeekRecord", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("GriffGym.Infrastructure.Persistence.Entities.UserRecord", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("GriffGym.Infrastructure.Persistence.Entities.WorkoutSessionRecord", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("GriffGym.Infrastructure.Persistence.Entities.WorkoutTemplateRecord", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
