package com.griffgym.infrastructure.security

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.GeneralSecurityException
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Encrypts and decrypts the token blob.
 *
 * A seam, not an abstraction for its own sake: the production implementation needs hardware
 * this process cannot have in a JVM test, and without this interface the storage class — where
 * the interesting logic actually is — could only be tested on a device.
 *
 * Both methods throw [GeneralSecurityException] rather than returning null. A key that has
 * vanished and a ciphertext that will not authenticate are different situations from "there is
 * nothing stored", and only the caller knows which of them warrants clearing the store.
 */
internal interface TokenCipher {

    /** Returns the IV followed by the ciphertext, as one self-describing blob. */
    @Throws(GeneralSecurityException::class)
    fun encrypt(plaintext: ByteArray): ByteArray

    @Throws(GeneralSecurityException::class)
    fun decrypt(payload: ByteArray): ByteArray
}

/**
 * AES-256/GCM under a key the Android Keystore holds and this process never sees.
 *
 * The key material is generated inside the Keystore and is not exportable: a rooted device or
 * an extracted app backup yields ciphertext and nothing to decrypt it with. That is the whole
 * point of storing a refresh token this way, since a refresh token *is* the account for as
 * long as it lives.
 *
 * Choices worth defending:
 *
 *  - **GCM, not CBC.** GCM authenticates as well as encrypts, so a tampered blob fails to
 *    decrypt instead of yielding plausible-looking rubbish that the JSON parser would then
 *    have to be trusted to reject.
 *  - **No padding**, because GCM is a stream mode and does not use any. Asking for PKCS7 here
 *    is rejected by the Keystore outright.
 *  - **`setUserAuthenticationRequired(false)`.** Requiring a device credential would mean the
 *    app could not refresh a token in the background — the sync worker runs while the phone is
 *    locked in a gym bag, which is exactly when it should.
 *  - **A fresh IV per encryption**, generated by the cipher rather than supplied. Reusing an
 *    IV under GCM is catastrophic, and the Keystore refuses a caller-supplied one on encrypt
 *    for precisely that reason.
 *
 * Not `androidx.security:security-crypto`. That library is deprecated, its `MasterKey` handling
 * has known corruption modes on multi-process access, and it would add a dependency to do
 * ninety lines of well-specified work.
 */
@Singleton
internal class AndroidKeystoreTokenCipher @Inject constructor() : TokenCipher {

    override fun encrypt(plaintext: ByteArray): ByteArray {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, secretKey())

        val iv = cipher.iv
        require(iv.size == IV_LENGTH_BYTES) {
            "Expected a $IV_LENGTH_BYTES-byte GCM IV, got ${iv.size}."
        }

        return iv + cipher.doFinal(plaintext)
    }

    override fun decrypt(payload: ByteArray): ByteArray {
        if (payload.size <= IV_LENGTH_BYTES) {
            throw GeneralSecurityException("Encrypted token blob is too short to contain an IV.")
        }

        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(
            Cipher.DECRYPT_MODE,
            secretKey(),
            GCMParameterSpec(TAG_LENGTH_BITS, payload, 0, IV_LENGTH_BYTES),
        )

        return cipher.doFinal(payload, IV_LENGTH_BYTES, payload.size - IV_LENGTH_BYTES)
    }

    /**
     * Looks the key up, creating it on first use.
     *
     * Generated lazily rather than at startup so that an installation which never signs in
     * never asks the Keystore for anything — on some devices that is a slow, occasionally
     * flaky call, and paying it on every cold start to support a feature the lifter declined
     * would be the wrong trade.
     */
    private fun secretKey(): SecretKey {
        val keyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        val existing = keyStore.getKey(KEY_ALIAS, null) as? SecretKey
        if (existing != null) return existing

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
        generator.init(
            KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(KEY_SIZE_BITS)
                .setUserAuthenticationRequired(false)
                .setRandomizedEncryptionRequired(true)
                .build(),
        )

        return generator.generateKey()
    }

    private companion object {
        const val ANDROID_KEYSTORE = "AndroidKeyStore"
        const val KEY_ALIAS = "griffgym_token_key"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val KEY_SIZE_BITS = 256
        const val TAG_LENGTH_BITS = 128

        /** GCM's standard nonce length. Anything else costs performance and buys nothing. */
        const val IV_LENGTH_BYTES = 12
    }
}
